---
theme: hugo-coder
languagecode: en
defaultcontentlanguage: en
params:
  author: Phivos Phivou
  info: A human platform engineer
  description: This is my space
  keywords: blog,developer,personal
  avatarurl: profile.jpg
  
  faviconSVG: favicon.svg
  favicon_32: favicon.png
  favicon_16: favicon.png

  since: 2024

  enableTwemoji: true

  colorScheme: auto
  hidecolorschemetoggle: false
  social:
  - name: Email
    icon: fa-solid fa-envelope fa-2x
    weight: 2
    url: mailto:phivos.phivou@gmail.com
  - name: Github
    icon: fa-brands fa-github fa-2x
    weight: 1
    url: https://gitlab.com/pheever
  - name: LinkedIn
    icon: fa-brands fa-linkedin fa-2x
    weight: 2
    url: https://www.linkedin.com/in/phivos-phivou-480062106
...